package keymapview

type Keycode struct{ Code, Label, Category string }

var Keycodes = []Keycode{
	{"A", "A", "Letters"},
	{"B", "B", "Letters"},
	{"C", "C", "Letters"},
	{"D", "D", "Letters"},
	{"E", "E", "Letters"},
	{"F", "F", "Letters"},
	{"G", "G", "Letters"},
	{"H", "H", "Letters"},
	{"I", "I", "Letters"},
	{"J", "J", "Letters"},
	{"K", "K", "Letters"},
	{"L", "L", "Letters"},
	{"M", "M", "Letters"},
	{"N", "N", "Letters"},
	{"O", "O", "Letters"},
	{"P", "P", "Letters"},
	{"Q", "Q", "Letters"},
	{"R", "R", "Letters"},
	{"S", "S", "Letters"},
	{"T", "T", "Letters"},
	{"U", "U", "Letters"},
	{"V", "V", "Letters"},
	{"W", "W", "Letters"},
	{"X", "X", "Letters"},
	{"Y", "Y", "Letters"},
	{"Z", "Z", "Letters"},
	{"N1", "1", "Numbers"},
	{"N2", "2", "Numbers"},
	{"N3", "3", "Numbers"},
	{"N4", "4", "Numbers"},
	{"N5", "5", "Numbers"},
	{"N6", "6", "Numbers"},
	{"N7", "7", "Numbers"},
	{"N8", "8", "Numbers"},
	{"N9", "9", "Numbers"},
	{"N0", "0", "Numbers"},
	{"LSHIFT", "L Shift", "Modifiers"},
	{"RSHIFT", "R Shift", "Modifiers"},
	{"LCTRL", "L Ctrl", "Modifiers"},
	{"RCTRL", "R Ctrl", "Modifiers"},
	{"LALT", "L Alt", "Modifiers"},
	{"RALT", "R Alt", "Modifiers"},
	{"LGUI", "L GUI", "Modifiers"},
	{"RGUI", "R GUI", "Modifiers"},
	{"UP", "Up", "Navigation"},
	{"DOWN", "Down", "Navigation"},
	{"LEFT", "Left", "Navigation"},
	{"RIGHT", "Right", "Navigation"},
	{"HOME", "Home", "Navigation"},
	{"END", "End", "Navigation"},
	{"PG_UP", "Page Up", "Navigation"},
	{"PG_DN", "Page Down", "Navigation"},
	{"MINUS", "-", "Punctuation"},
	{"EQUAL", "=", "Punctuation"},
	{"LBKT", "[", "Punctuation"},
	{"RBKT", "]", "Punctuation"},
	{"BSLH", "\\", "Punctuation"},
	{"SEMI", ";", "Punctuation"},
	{"SQT", "'", "Punctuation"},
	{"GRAVE", "`", "Punctuation"},
	{"COMMA", ",", "Punctuation"},
	{"DOT", ".", "Punctuation"},
	{"FSLH", "/", "Punctuation"},
	{"NON_US_HASH", "#", "Punctuation"},
	{"EXCL", "!", "Shifted Symbols"},
	{"AT", "@", "Shifted Symbols"},
	{"HASH", "#", "Shifted Symbols"},
	{"DLLR", "$", "Shifted Symbols"},
	{"PRCNT", "%", "Shifted Symbols"},
	{"CARET", "^", "Shifted Symbols"},
	{"AMPS", "&", "Shifted Symbols"},
	{"STAR", "*", "Shifted Symbols"},
	{"LPAR", "(", "Shifted Symbols"},
	{"RPAR", ")", "Shifted Symbols"},
	{"UNDER", "_", "Shifted Symbols"},
	{"PLUS", "+", "Shifted Symbols"},
	{"LBRC", "{", "Shifted Symbols"},
	{"RBRC", "}", "Shifted Symbols"},
	{"PIPE", "|", "Shifted Symbols"},
	{"COLON", ":", "Shifted Symbols"},
	{"DQT", "\"", "Shifted Symbols"},
	{"TILDE", "~", "Shifted Symbols"},
	{"LT", "<", "Shifted Symbols"},
	{"GT", ">", "Shifted Symbols"},
	{"QMARK", "?", "Shifted Symbols"},
	{"ESC", "Esc", "Control"},
	{"RET", "Enter", "Control"},
	{"SPACE", "Space", "Control"},
	{"TAB", "Tab", "Control"},
	{"BSPC", "Backspace", "Control"},
	{"DEL", "Delete", "Control"},
	{"INS", "Insert", "Control"},
	{"CAPS", "Caps Lock", "Control"},
	{"PSCRN", "Print Screen", "Control"},
	{"SLCK", "Scroll Lock", "Control"},
	{"PAUSE_BREAK", "Pause", "Control"},
	{"F1", "F1", "Function"},
	{"F2", "F2", "Function"},
	{"F3", "F3", "Function"},
	{"F4", "F4", "Function"},
	{"F5", "F5", "Function"},
	{"F6", "F6", "Function"},
	{"F7", "F7", "Function"},
	{"F8", "F8", "Function"},
	{"F9", "F9", "Function"},
	{"F10", "F10", "Function"},
	{"F11", "F11", "Function"},
	{"F12", "F12", "Function"},
	{"F13", "F13", "Function"},
	{"F14", "F14", "Function"},
	{"F15", "F15", "Function"},
	{"F16", "F16", "Function"},
	{"F17", "F17", "Function"},
	{"F18", "F18", "Function"},
	{"F19", "F19", "Function"},
	{"F20", "F20", "Function"},
	{"F21", "F21", "Function"},
	{"F22", "F22", "Function"},
	{"F23", "F23", "Function"},
	{"F24", "F24", "Function"},
	{"KP_N1", "KP 1", "Keypad"},
	{"KP_N2", "KP 2", "Keypad"},
	{"KP_N3", "KP 3", "Keypad"},
	{"KP_N4", "KP 4", "Keypad"},
	{"KP_N5", "KP 5", "Keypad"},
	{"KP_N6", "KP 6", "Keypad"},
	{"KP_N7", "KP 7", "Keypad"},
	{"KP_N8", "KP 8", "Keypad"},
	{"KP_N9", "KP 9", "Keypad"},
	{"KP_N0", "KP 0", "Keypad"},
	{"KP_DOT", "KP .", "Keypad"},
	{"KP_PLUS", "KP +", "Keypad"},
	{"KP_MINUS", "KP -", "Keypad"},
	{"KP_MULTIPLY", "KP *", "Keypad"},
	{"KP_DIVIDE", "KP /", "Keypad"},
	{"KP_ENTER", "KP Enter", "Keypad"},
	{"KP_EQUAL", "KP =", "Keypad"},
	{"C_MUTE", "Mute", "Media"},
	{"C_VOL_UP", "Vol Up", "Media"},
	{"C_VOL_DN", "Vol Down", "Media"},
	{"C_PP", "Play/Pause", "Media"},
	{"C_NEXT", "Next", "Media"},
	{"C_PREV", "Previous", "Media"},
	{"C_STOP", "Stop", "Media"},
	{"C_BRI_UP", "Bright Up", "Media"},
	{"C_BRI_DN", "Bright Down", "Media"},
}

var displayOverrides = map[string]string{
	"UP":                "▲",
	"DOWN":              "▼",
	"LEFT":              "◀\uFE0E",
	"RIGHT":             "▶\uFE0E",
	"BSPC":              "⌫",
	"DEL":               "⌦",
	"RET":               "Enter",
	"SPACE":             "Space",
	"CAPS":              "Caps",
	"PG_UP":             "PgUp",
	"PG_DN":             "PgDn",
	"INS":               "Ins",
	"PSCRN":             "PrtSc",
	"SLCK":              "ScrLk",
	"LSHIFT":            "⇧",
	"RSHIFT":            "⇧R",
	"LCTRL":             "⌃",
	"RCTRL":             "⌃R",
	"LALT":              "⌥",
	"RALT":              "⌥R",
	"LGUI":              "⌘",
	"RGUI":              "⌘R",
	"LEFT_SHIFT":        "⇧",
	"RIGHT_SHIFT":       "⇧R",
	"LSHFT":             "⇧",
	"RSHFT":             "⇧R",
	"LEFT_ALT":          "⌥",
	"RIGHT_ALT":         "⌥R",
	"LEFT_CTRL":         "⌃",
	"LEFT_CONTROL":      "⌃",
	"LCTL":              "⌃",
	"RIGHT_CTRL":        "⌃R",
	"RIGHT_CONTROL":     "⌃R",
	"RCTL":              "⌃R",
	"LEFT_GUI":          "⌘",
	"RIGHT_GUI":         "⌘R",
	"APOS":              "'",
	"PERIOD":            ".",
	"SLASH":             "/",
	"BSLASH":            "\\",
	"ESCAPE":            "Esc",
	"RETURN":            "Enter",
	"ENTER":             "Enter",
	"BACKSPACE":         "⌫",
	"DELETE":            "⌦",
	"EXCLAMATION":       "!",
	"EXCL":              "!",
	"AT_SIGN":           "@",
	"AT":                "@",
	"HASH":              "#",
	"POUND":             "#",
	"DOLLAR":            "$",
	"DLLR":              "$",
	"PERCENT":           "%",
	"PRCNT":             "%",
	"CARET":             "^",
	"AMPS":              "&",
	"AMPERSAND":         "&",
	"STAR":              "*",
	"ASTERISK":          "*",
	"LEFT_PARENTHESIS":  "(",
	"LPAR":              "(",
	"RIGHT_PARENTHESIS": ")",
	"RPAR":              ")",
	"UNDER":             "_",
	"PLUS":              "+",
	"LEFT_BRACE":        "{",
	"LBRC":              "{",
	"RIGHT_BRACE":       "}",
	"RBRC":              "}",
	"PIPE":              "|",
	"COLON":             ":",
	"DOUBLE_QUOTES":     "\"",
	"DQT":               "\"",
	"LESS_THAN":         "<",
	"LT":                "<",
	"GREATER_THAN":      ">",
	"GT":                ">",
	"QUESTION":          "?",
	"QMARK":             "?",
	"NON_US_BSLH":       "\\",
}

var modifierSymbols = map[string]string{
	"LC": "⌃",
	"RC": "⌃",
	"LS": "⇧",
	"RS": "⇧",
	"LA": "⌥",
	"RA": "⌥",
	"LG": "⌘",
	"RG": "⌘",
}

var hebrewLabels = map[string]string{
	"Q":      "/",
	"W":      "\u05F3",
	"E":      "\u05E7",
	"R":      "\u05E8",
	"T":      "\u05D0",
	"Y":      "\u05D8",
	"U":      "\u05D5",
	"I":      "\u05DF",
	"O":      "\u05DD",
	"P":      "\u05E4",
	"A":      "\u05E9",
	"S":      "\u05D3",
	"D":      "\u05D2",
	"F":      "\u05DB",
	"G":      "\u05E2",
	"H":      "\u05D9",
	"J":      "\u05D7",
	"K":      "\u05DC",
	"L":      "\u05DA",
	"SEMI":   "\u05E3",
	"APOS":   ",",
	"Z":      "\u05D6",
	"X":      "\u05E1",
	"C":      "\u05D1",
	"V":      "\u05D4",
	"B":      "\u05E0",
	"N":      "\u05DE",
	"M":      "\u05E6",
	"COMMA":  "\u05EA",
	"PERIOD": "\u05E5",
	"SLASH":  ".",
}

var KeyNames = []string{
	"LC1", "LC2", "LC3", "LC4", "LC5", "RC1", "RC2", "RC3", "RC4", "RC5", "LN1", "LN2", "LN3", "LN4", "LN5", "LN6", "RN1", "RN2", "RN3", "RN4", "RN5", "RN6", "LT1", "LT2", "LT3", "LT4", "LT5", "LT6", "RT1", "RT2", "RT3", "RT4", "RT5", "RT6", "LM1", "LM2", "LM3", "LM4", "LM5", "LM6", "RM1", "RM2", "RM3", "RM4", "RM5", "RM6", "LB1", "LB2", "LB3", "LB4", "LB5", "LB6", "LH1", "LH2", "LH3", "RH1", "RH2", "RH3", "RB1", "RB2", "RB3", "RB4", "RB5", "RB6", "LF1", "LF2", "LF3", "LF4", "LF5", "LH4", "LH5", "LH6", "RH4", "RH5", "RH6", "RF1", "RF2", "RF3", "RF4", "RF5",
}

// Geometry retains each physical key position; -1 marks empty space.
var Geometry = [][]int{
	{0, 1, 2, 3, 4, -1, -1, -1, -1, -1, -1, -1, -1, -1, 5, 6, 7, 8, 9},
	{10, 11, 12, 13, 14, 15, -1, -1, -1, -1, -1, -1, -1, 16, 17, 18, 19, 20, 21},
	{22, 23, 24, 25, 26, 27, -1, -1, -1, -1, -1, -1, -1, 28, 29, 30, 31, 32, 33},
	{34, 35, 36, 37, 38, 39, -1, -1, -1, -1, -1, -1, -1, 40, 41, 42, 43, 44, 45},
	{46, 47, 48, 49, 50, 51, -1, -1, -1, -1, -1, -1, -1, 58, 59, 60, 61, 62, 63},
	{64, 65, 66, 67, 68, -1, 52, 53, 54, -1, 55, 56, 57, -1, 75, 76, 77, 78, 79},
	{-1, -1, -1, -1, -1, -1, 69, 70, 71, -1, 72, 73, 74, -1, -1, -1, -1, -1, -1},
}
